global:

  configuration:
    nginx:
      name: nginx
      srvc: test-nginx
      enabled: true
      replicaCount: 2
      image:
        repository: 250738637992.dkr.ecr.eu-west-1.amazonaws.com/argo/nginx
        tag: v1
        pullPolicy: IfNotPresent
      imagePullSecrets:
        name: ecr-regcred
      namespace: default
      ContainerPort: 80
      ingress:
        host: argo.example.com

    python:
      name: python
      srvc: test-python
      enabled: true
      replicaCount: 1
      image:
        repository: 250738637992.dkr.ecr.eu-west-1.amazonaws.com/argo/project-argo
        tag: latest
        pullPolicy: IfNotPresent
      imagePullSecrets:
        name: ecr-regcred
      namespace: python
      ContainerPort: 80
      ingress:
        host: cipheronic.com
