{{- range .Values.global.configuration }}
{{- if and (eq (toString .srvc) (toString $.Values.name)) (eq (toString .enabled) "true") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
        - containerPort: {{ .ContainerPort}}
      imagePullSecrets:
      - name: {{ .imagePullSecrets.name }}

{{- end }}
{{- end }}
