apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-nginx
  template:
    metadata:
      labels:
        app: webapp-nginx
    spec:
      containers:
        - name: nginx
          image: 250738637992.dkr.ecr.eu-west-1.amazonaws.com/argo/nginx:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-regcred
